apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-tailscale
  namespace: eleduck-analytics
  annotations:
    tailscale.com/tailnet-fqdn: analytics.tail6fbc5.ts.net
    tailscale.com/tags: tag:k8s-pedro-ops,tag:production
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: metabase
      port:
        number: 3000
  tls:
    - hosts:
        - analytics
